FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime
WORKDIR /app
COPY docker/requirements-dca.txt .
RUN pip install --no-cache-dir -r requirements-dca.txt
COPY dca_server/ /app/dca_server/
EXPOSE 8300
CMD ["python", "-m", "dca_server.server"]
