FROM python:3.10-slim

WORKDIR /app

COPY docker/requirements-django.txt .
RUN pip install --no-cache-dir -r requirements-django.txt

COPY . /app

EXPOSE 9001

CMD ["python", "frontend/manage.py", "runserver", "0.0.0.0:9001"]
