"""MedDRA coding module — lookup table + MedGemma fallback.

Strategy (doc_agent.md §6.6):
  ① AACT/FAERS lookup table matching (highest accuracy)
  ② MedGemma 27B inference with confidence score
  ③ Manual review flag (low confidence < 0.85)

Lookup table is loaded from ``data/meddra_lookup.json``, which is generated
by ``scripts/build_meddra_lookup.py`` using openFDA FAERS + optional AACT data.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Optional

from openai import OpenAI

from .schemas.agent_output import MedDRACode

logger = logging.getLogger(__name__)

MEDDRA_CONFIDENCE_THRESHOLD = 0.85

MEDGEMMA_MEDDRA_PROMPT = """\
You are a pharmacovigilance coding specialist. Given an adverse event term reported in a clinical trial, \
provide the most accurate MedDRA coding.

Adverse Event Term: "{ae_term}"

Respond ONLY with a JSON object (no markdown, no explanation):
{{
  "pt": "MedDRA Preferred Term",
  "pt_code": "MedDRA PT code (8-digit number)",
  "soc": "System Organ Class",
  "llt": "Lowest Level Term (closest to the reported term)",
  "confidence": 0.95
}}

Rules:
- Use MedDRA v26.1 terminology
- PT must be an official MedDRA Preferred Term
- SOC must be one of the 27 official MedDRA System Organ Classes
- LLT should be the closest match to the original reported term
- confidence: 0.0-1.0, how certain you are this is the correct PT mapping
- If unsure, set confidence below 0.85
"""

# ---------------------------------------------------------------------------
# AACT/FAERS lookup table — loaded from data/meddra_lookup.json
# Generated by: python scripts/build_meddra_lookup.py
# Sources: openFDA FAERS (8 ADC drugs) + optional AACT (ClinicalTrials.gov)
# ---------------------------------------------------------------------------

_LOOKUP_PATH = Path(__file__).resolve().parent / "data" / "meddra_lookup.json"

# Verified PT codes for common ADC terms (MedDRA v26.1).
# These are preserved when loading from the FAERS JSON (which has no codes).
_VERIFIED_PT_CODES: dict[str, str] = {
    "pneumonitis": "10035742",
    "interstitial lung disease": "10022611",
    "nausea": "10028813",
    "vomiting": "10047700",
    "diarrhoea": "10012735",
    "fatigue": "10016256",
    "asthenia": "10003549",
    "alopecia": "10001760",
    "neutropenia": "10029354",
    "febrile neutropenia": "10016288",
    "thrombocytopenia": "10043554",
    "anaemia": "10002034",
    "decreased appetite": "10061428",
    "constipation": "10010774",
    "stomatitis": "10042128",
    "rash": "10037844",
    "peripheral sensory neuropathy": "10034620",
    "keratitis": "10023332",
    "palmar-plantar erythrodysaesthesia syndrome": "10033553",
    "infusion related reaction": "10051792",
    "hepatotoxicity": "10019851",
    "electrocardiogram qt prolonged": "10014387",
    "left ventricular dysfunction": "10024119",
    "ejection fraction decreased": "10050528",
    "cough": "10011224",
    "dyspnoea": "10013968",
    "headache": "10019211",
    "pyrexia": "10037660",
    "abdominal pain": "10000081",
    "hypokalaemia": "10021015",
    "alanine aminotransferase increased": "10001551",
    "aspartate aminotransferase increased": "10003481",
    "blood bilirubin increased": "10005364",
    "mucosal inflammation": "10028116",
    "sepsis": "10040047",
    "pneumonia": "10035664",
    "hypertension": "10020772",
    "hypotension": "10021097",
    "proteinuria": "10037032",
    "weight decreased": "10047895",
}

# Alias mappings: variant spelling → canonical key in lookup
_ALIASES: dict[str, str] = {
    "ild": "interstitial lung disease",
    "diarrhea": "diarrhoea",
    "anemia": "anaemia",
    "dyspnea": "dyspnoea",
    "fever": "pyrexia",
    "hypokalemia": "hypokalaemia",
    "hand-foot syndrome": "palmar-plantar erythrodysaesthesia syndrome",
    "qt prolongation": "electrocardiogram qt prolonged",
    "peripheral neuropathy": "peripheral sensory neuropathy",
    "mucositis": "mucosal inflammation",
    # US → UK spelling (MedDRA uses British English)
    "hyperglycemia": "hyperglycaemia",
    "hypercalcemia": "hypercalcaemia",
    "hyperkalemia": "hyperkalaemia",
    "hyperbilirubinemia": "hyperbilirubinaemia",
    "hyperuricemia": "hyperuricaemia",
    "hypoalbuminemia": "hypoalbuminaemia",
    "hypocalcemia": "hypocalcaemia",
    "hypomagnesemia": "hypomagnesaemia",
    "hyponatremia": "hyponatraemia",
    "hypophosphatemia": "hypophosphataemia",
    "leukemia": "acute myeloid leukaemia",
    "bacteremia": "bacteraemia",
}


def _load_lookup() -> dict[str, dict[str, str | None]]:
    """Load the FAERS/AACT lookup table from JSON, enriched with verified PT codes."""
    lookup: dict[str, dict[str, str | None]] = {}

    if _LOOKUP_PATH.exists():
        try:
            with open(_LOOKUP_PATH, encoding="utf-8") as f:
                data = json.load(f)
            raw_terms = data.get("terms", {})
            for key, info in raw_terms.items():
                pt_name = info.get("pt", key.title())
                pt_lower = pt_name.strip().lower()
                # Look up verified code by key or PT name
                pt_code = _VERIFIED_PT_CODES.get(key) or _VERIFIED_PT_CODES.get(pt_lower)
                lookup[key] = {
                    "pt": pt_name,
                    "pt_code": pt_code,
                    "soc": info.get("soc"),
                    "llt": info.get("llt", pt_name),
                }
            logger.info(
                "MedDRA lookup loaded: %d terms from %s", len(lookup), _LOOKUP_PATH,
            )
        except Exception:
            logger.exception("Failed to load MedDRA lookup from %s", _LOOKUP_PATH)
    else:
        logger.warning(
            "MedDRA lookup file not found: %s — run scripts/build_meddra_lookup.py",
            _LOOKUP_PATH,
        )

    # Add aliases
    for alias, canonical in _ALIASES.items():
        if canonical in lookup and alias not in lookup:
            entry = dict(lookup[canonical])
            entry["llt"] = alias.title()  # LLT = the alias form
            lookup[alias] = entry

    return lookup


FAERS_LOOKUP: dict[str, dict[str, str | None]] = _load_lookup()


# ---------------------------------------------------------------------------
# Step ②: MedGemma fallback
# ---------------------------------------------------------------------------

def _code_via_medgemma(
    term: str,
    base_url: str = "http://localhost:38000/v1",
    model_id: str = "google/medgemma-27b-it",
    api_key: str = "EMPTY",
) -> MedDRACode:
    """Call MedGemma 27B to infer MedDRA coding for an unknown AE term."""
    client = OpenAI(base_url=base_url, api_key=api_key)

    prompt = MEDGEMMA_MEDDRA_PROMPT.format(ae_term=term)

    response = client.chat.completions.create(
        model=model_id,
        messages=[{"role": "user", "content": prompt}],
        max_tokens=256,
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()

    # Strip markdown code fences if present
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
        if raw.endswith("```"):
            raw = raw[:-3]
        raw = raw.strip()

    parsed = json.loads(raw)
    confidence = float(parsed.get("confidence", 0.0))

    source = "medgemma" if confidence >= MEDDRA_CONFIDENCE_THRESHOLD else "manual_review"
    if source == "manual_review":
        logger.warning(
            "MedDRA coding low confidence for '%s': %.2f < %.2f — flagged for manual review",
            term, confidence, MEDDRA_CONFIDENCE_THRESHOLD,
        )

    return MedDRACode(
        pt=parsed.get("pt", term),
        pt_code=parsed.get("pt_code"),
        soc=parsed.get("soc"),
        llt=parsed.get("llt", term),
        confidence=confidence,
        source=source,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def code_meddra(
    term: str,
    use_medgemma: bool = True,
    base_url: str = "http://localhost:38000/v1",
    model_id: str = "google/medgemma-27b-it",
    api_key: str = "EMPTY",
) -> MedDRACode:
    """Look up MedDRA coding for an AE term.

    Strategy (3-step, doc_agent.md §6.6):
      ① AACT/FAERS lookup table matching → highest accuracy
      ② MedGemma 27B inference → confidence score
      ③ Manual review flag → confidence < 0.85
    """
    # Step ①: FAERS/AACT lookup table
    key = term.strip().lower()
    if key in FAERS_LOOKUP:
        entry = FAERS_LOOKUP[key]
        return MedDRACode(
            pt=entry["pt"],
            pt_code=entry.get("pt_code"),
            soc=entry.get("soc"),
            llt=entry.get("llt"),
            confidence=1.0,
            source="lookup",
        )

    # Step ② + ③: MedGemma fallback (with auto manual_review flag)
    if use_medgemma:
        try:
            result = _code_via_medgemma(term, base_url, model_id, api_key)
            logger.info(
                "MedDRA via MedGemma: '%s' → PT='%s' (confidence=%.2f, source=%s)",
                term, result.pt, result.confidence or 0.0, result.source,
            )
            return result
        except Exception:
            logger.exception("MedGemma MedDRA coding failed for '%s', returning raw term", term)

    # Final fallback: return term as-is, flagged for manual review
    return MedDRACode(
        pt=term,
        pt_code=None,
        soc=None,
        llt=term,
        confidence=0.0,
        source="manual_review",
    )
